include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - annotate_overrides
    - constant_identifier_names
    - one_member_abstracts
    - sort_constructors_first
    - unnecessary_brace_in_string_interps
